openapi: 3.0.1
info:
  title: Emp
  description: API Definition of Emp
  version: 1.0.3
servers:
- url: http://localhost:8290/emp
paths:
  /all:
    get:
      responses:
        default:
          description: Default response
  /women:
    get:
      responses:
        default:
          description: Default response
  /men:
    get:
      responses:
        default:
          description: Default response
  /employees/{employeeId}:
    get:
      parameters:
      - name: employeeId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /login:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /employees:
    get:
      responses:
        default:
          description: Default response
  /employees/full:
    get:
      responses:
        default:
          description: Default response
  /reports:
    get:
      responses:
        default:
          description: Default response
  /admin/users:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /upload/resume:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /encrypt:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /search:
    get:
      responses:
        default:
          description: Default response
  /config:
    get:
      responses:
        default:
          description: Default response
  /proxy:
    get:
      responses:
        default:
          description: Default response
